
services:

  product_service:
    build:
      context: .
      dockerfile: ./productService/Dockerfile
    container_name: product
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - RABBIT_MQ_ADDRESS=amqp://guest:guest@rabbitmq:5672/
      - POSTGRES_HOST=postgres://postgres:password@psql:5432/postgres
    depends_on:
      psql:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    environment:
      - ProductServiceURL=dns:///product:9090
      - OrderServiceURL=dns:///order:9091
    ports:
      - 8084:8084
    depends_on:
      - product_service
      - order_service
  notification_service:
    build:
      context: .
      dockerfile: ./notificationService/Dockerfile
    container_name: notifications
    ports:
      - 8081:8081
    environment:
      - RABBIT_MQ_ADDRESS=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      psql:
          condition: service_started
      rabbitmq:
        condition: service_healthy
  order_service:
    build:
      context: .
      dockerfile: ./orderService/Dockerfile
    container_name: order
    ports:
      - 8083:8083
      - 9091:9091
    environment:
      - HOST=postgres://postgres:password@psql:5432/postgres
      - GRPC_PORT=9091
      - GRPC_PRODUCT_ADDRESS=dns:///product:9090
    depends_on:
      psql:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      product_service:
        condition: service_started
  psql:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
    volumes:
      - ./init-scripts:/init-multiple-dbs.sql
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 15s
      retries: 5
  migrator:
    image: migrate/migrate
    depends_on:
      psql:
        condition: service_started
    volumes:
      - ./productService/product/infrastructure/postgres/migrations:/migrations-product
      - ./orderService/order/infrastructure/postgres/migrations:/migrations-order
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        migrate -path=/migrations-product -database=postgres://postgres:password@psql:5432/postgres?sslmode=disable up &&
        migrate -path=/migrations-order -database=postgres://postgres:password@psql:5432/postgres?sslmode=disable up
